### ISSUE TITLE
Expandable Fortune.js store

### ISSUE THREAD

**Issue by yostools** [genie-team/graphql-genie#16]
It would be useful to be able to extend and use the Fortune.js store outside of GraphQL Genie or to pass an already created store to GraphQL Genie.

**Comment by acoreyj** [comment]
You can get the Fortune.js store actually

`genie.getDataResolver().getStore()`

Probably generally better to use the CRUD calls on the dataResolver but could be cases you would want the Fortune store.

https://github.com/genie-team/graphql-genie/blob/master/docs/GraphQLGenieAPI.md#getdataresolver

Not sure it's possible to add types to fortune outside the constructor so would make it difficult to be able to pass in an existing store.

**Comment by yostools** [comment]
I haven't found a way to extend a store yet, so I created a pull request that allows you to pass external Fortune.js record type definitions, which are then combined with Genie's definitions before initializing the store. See https://github.com/genie-team/graphql-genie/pull/17.
