### ISSUE TITLE
[Question/Bug] Allowing for Schema Evolution

### ISSUE THREAD

**Issue by ecwyne** [genie-team/graphql-genie#9]
I am trying to figure out if I am able to change my schema over time. As a test I ran the following schema

```graphql
interface Human {
  id: ID!
  name: String
}

type Boy implements Human {
  id: ID!
  name:String!
  sisters: [Girl]!
}

type Girl implements Human {
  id: ID!
  name:String!
  brothers: [Boy]!
}
```

(Using IndexedDB) I see that a `Boy_Girl_Human` table is created and items have a `Boy_Girl_Human_[id]` structure.

Adding the following to my schema (not changing the other types at all)
```graphql
type Father implements Human {
  id: ID!
  name: String!
  sons: [Boy]!
}
```
A `Boy_Father_Girl_Human` table is created and items have a `Boy_Father_Girl_Human_[id]` structure. This actually breaks https://genie-team.github.io/graphql-genie-client and queries/mutations do not go through at all (until I delete the IndexedDB)

How can I structure things to be able to make changes to my schema definition without breaking my database?

**Comment by acoreyj** [comment]
* Implemented @storeName [custom directive](https://github.com/genie-team/graphql-genie/blob/master/docs/sdl.md#custom-directives-you-can-use) to better facilitate altering schema
* Added documentation on [altering your schema](https://github.com/genie-team/graphql-genie/blob/master/docs/sdl.md#altering-your-schema)
